# Copyright Jeron Lau 2017 - 2019.
# Dual-licensed under either the MIT License or the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at https://www.boost.org/LICENSE_1_0.txt)

# XXXX  X                    /5\——————/5\       XXXX      X           X
# X   X X   XXX   XXXX      |   0    0   |     X      XXX   XXXX XXXX X X   X
# X   X X  X   X  X   X  /"\|     <>     |/"\  X      X   X    X    X X X   X
# XXXX  X  X   X  X   X  \  \\_  ====  _//  /  X   XX X   X   X    X  X  X X
# X     X  X   X  XXXX    \_              _/   X    X X   X  X    X   X   X
# X     X   XXX   X       / \            / \    XXXX  X   X XXXX XXXX X   X
#                 X       \                /                            XX
#                          --____________--

[package]
name = "barg"
version = "0.0.3"
authors = [
	"Jeron Lau <jeron.lau@plopgrizzly.com>",
]
edition = "2018"
license = "MIT / BSL-1.0"
documentation = "https://docs.rs/barg"
homepage = "https://free.plopgrizzly.com/barg"
repository = "https://github.com/plopgrizzly/barg"
readme = "README.md"
description = "3D vector graphics renderer."
keywords = ["graphics", "render", "vector", "3D", "render"]
categories = ["gui", "multimedia", "rendering::graphics-api"]

[dependencies]
# For Text Rendering
fonterator = { path = "../fonterator" } # "0.3"
# Renderer
footile = { path = "../footile" } # "0.2"

[dev-dependencies]
png = "0.13"
